### ISSUE TITLE
Images doesn't show on template and more than one field not works

### ISSUE THREAD

**Issue by reypm** [jerel/folder#2]
Hi I'm having two issues:
1) when I create two fields using Folder type first doesn't work I can't select images 
2) after save the page I can't see any images in the created page. 

I'm using PyroCMS Community 2.2.1 and a template file for my page type. This is the code I'm using for show images:

```
<ul class="slides">
  {{ imagenes_slider }}
    <li><img src="{{ url:site }}files/thumb/{{ id }}" alt="{{ name }}" /></li>
  {{ /imagenes_slider }}
</ul>

{{ promociones }}
 <li class="col3 item">
   <div class="view"><img src="{{ url:site }}files/thumb/{{ id }}" alt="{{ name }}" /></div>
 </li>
{{ /promociones }}
```

Of course imagenes_slider and promociones are the slugs for the field Folder types, any help?

**Comment by jerel** [comment]
At this time there's no way to use more than one instance of the Folder field type on the same page. It's main use is to allow many files to be uploaded to one page/stream entry and managed.

As for the images not displaying: try removing one of those instances... does it work then? It works for me but I just have one instance.

**Comment by madbonkey** [comment]
We should work on the multiple instances per page thing, though. Having the ability to dynamically create hidden folders in the background and attaching files to a stream entry is huge! I have a client right now that needs this functionality, but I can think of many other use cases (car vendor: image galleries for interior, exterior images and PDF listing, for example).

Why does it currently not work? As far as I can see, the JS for the editor would have to be adjusted to allow for multiple folders, right?
